TRUNCATE TABLE users, posts RESTART IDENTITY;

-- ORIGINAL PASSWORDS:
  -- ["james01", "test123"]
  -- ["lizfriz39", "test2143"]
  -- ["henrydacoolguy55", "test9876"]
  -- ["francescafrey38", "test54523"]
  -- ["jackimmature69", "345test"]
  -- ["moneygurl4Hash", "test32462"]

INSERT INTO users (user_name, first_name, last_name, email, password, birth_date, location, is_admin) VALUES ('james01', 'James', 'Smith', 'james@fs.com', '$2b$10$DYW8l8xouP2G6akT6mZzNuwtVbVQLXrolq1f/q5s5cxyJhloHDQcO', '2000-05-21', 'New York', true);
INSERT INTO users (user_name, first_name, last_name, email, password, birth_date, location, is_admin) VALUES ('lizfriz39', 'Liz', 'Friz', 'friz@fs.com', '$2b$10$XbpzPyXwxo.KkAKVJjxjHeCNZ8.bmHzMPFqeD2KZjRZpLvteMSTrC', '1995-08-03', 'Chicago', true);
INSERT INTO users (user_name, first_name, last_name, email, password, birth_date, location) VALUES ('henrydacoolguy55', 'Henry', 'David', 'hdavid@fs.com', '$2b$10$fsix9sPuOC2OwntNWkJAMOqidcwTOkvn3OtiAoLMz683ASZksyKbG', '1975-01-13', 'New York');
INSERT INTO users (user_name, first_name, last_name, email, password, birth_date, location) VALUES ('francescafrey38', 'Francesca', 'Frey', 'frannyfrey@fs.com', '$2b$10$NpqpxTD6T4Xx/LO/VZ9Q2ewD/QuSVhvQICtgmCJJEe/j4fMCKSm7u', '2002-09-18', 'Los Angeles');
INSERT INTO users (user_name, first_name, last_name, email, password, birth_date, location) VALUES ('jackimmature69', 'Jack', 'Johnson', 'jackattack@fs.com', '$2b$10$4XCjRihndWcJJ2eWCs8iOu3VtLKs3rCvxyckyvioIOfNP4SrD2zUm', '2005-07-30', 'Georgia');
INSERT INTO users (user_name, first_name, last_name, email, password, birth_date, location) VALUES ('moneygurl4', 'Monica', 'Zelynski', 'mz@fs.com', '$2b$10$vcvLIbnnYTNQsjSV2XRftus1Ch8GJbYPnTzNtwceHCXLENc.9YXde', '1999-05-05', 'Texas');


INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='james01'), 'Fianto Duri, the complete tutorial', 'Fianto Duri is a charm that was created to be combined with protective spells (Can be used with another person''s shield spell)(When used on something else creates a explosion). As we already knows the (i.e.) Shield Charm needs the caster to stay focused on the spell in order to continue protecting him, so Fianto Duri allows the caster to keep a charm “alive” while he does some other work or casts some other spells.', 'crime', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='lizfriz39'), 'Untransfiguration classes to become compulsory at Hogwarts', 'Learning untransfiguration is going to be mandatory at Hogwarts School of Witchcraft and Wizardry from 2017 onward. Untransfiguration will be covered in beginner-level spellbooks such as A Beginner''s Guide to Transfiguration. Failure to at least attempt to untranfigure a wrongly-done transfiguration will be considered irresponsible.', 'technology', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='henrydacoolguy55'), 'Cracking the Aurologist Interview', 'Now in the 5th edition, Cracking the Aurologist Interview gives you the interview preparation you need to get the top aura study jobs. The book is over 500 pages and includes 150 aurologist interview questions and answers, as well as other advice.', 'sports', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='francescafrey38'), 'ASK WN: What do you use to digitalize your scrolls?', 'Some scrolls need conservation treatment before they can be safely transported, handled, and digitized.  After these questions are answered, Preservation and Information Technology Specialists assess the project requirements and create the digitilized version.', 'entertainment', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='henrydacoolguy55'), 'The Pragmatic Dragon Feeder', 'In The Pragmatic Dragon Feeder, the author Baruffio tell us how to give food to dragons in a way that we can follow. How did they get so smart? Aren''t they just as focused on details as other dragon feeders? The answer is that they paid attention to what they were doing while they were doing it.', 'sports', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='moneygurl4'), 'The complete quidditch statistics', 'This is the Complete source for quidditch history including complete player, team, and league stats, awards, records, leaders, rookies and scores.', 'technology', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
INSERT INTO posts (user_id, title, content, category, image_url) VALUES ((SELECT id from users where user_name='jackimmature69'), 'The complete quidditch statistics', 'This is the Complete source for quidditch history including complete player, team, and league stats, awards, records, leaders, rookies and scores.', 'news', 'https://media.istockphoto.com/photos/innovation-and-science-concept-picture-id1177116437?k=20&m=1177116437&s=612x612&w=0&h=3aeSq8Wv-6gcpFzuUz40e62Xs_zKMDuSLDz79BshuZg=');
